export const CONFIG = {
  GAME_WIDTH: 480,
  GAME_HEIGHT: 640,

  // Player
  PLAYER_RADIUS: 12,
  PLAYER_FOLLOW_SPEED: 12,
  PLAYER_DEFAULT_HP: 3,
  INVULN_DURATION: 0.8,
  PLAYER_TRAIL_LENGTH: 8,

  // Near-miss
  NEAR_MISS_THRESHOLD: 28,
  NEAR_MISS_BASE_POINTS: 80,
  NEAR_MISS_COMBO_WINDOW: 1.5,
  NEAR_MISS_MAX_COMBO: 5,

  // Scoring
  TIME_SCORE_PER_SECOND: 50,
  SURVIVAL_MILESTONES: [30, 60, 90, 120, 150] as readonly number[],
  MILESTONE_BONUSES: [500, 1000, 1500, 2000, 2500] as readonly number[],

  // Timing
  COUNTDOWN_STEP_DURATION: 0.8,
  DEATH_ANIM_DURATION: 1.2,
  DEATH_FREEZE_DURATION: 0.15,
  DEATH_SLOWMO_DURATION: 0.5,
  DEATH_SLOWMO_SCALE: 0.2,
  HIT_SLOWMO_DURATION: 0.12,
  HIT_SLOWMO_SCALE: 0.3,
  RESULTS_DELAY: 0.4,
  MAX_DELTA_TIME: 0.05,

  // Difficulty
  BASE_RIFT_SPAWN_INTERVAL: 4.0,
  MIN_RIFT_SPAWN_INTERVAL: 1.2,
  BASE_PROJECTILE_SPEED: 120,
  MAX_PROJECTILE_SPEED: 280,
  BASE_ACTIVE_RIFT_CAP: 2,
  MAX_ACTIVE_RIFT_CAP: 5,
  BASE_RIFT_LIFETIME: 3.0,
  MIN_RIFT_LIFETIME: 1.5,
  DIFFICULTY_TIME_CONSTANT: 80,

  // Projectiles
  ORB_RADIUS: 5,
  BOLT_RADIUS: 3,
  WAVE_RADIUS: 8,
  BOLT_SPEED_MULT: 1.5,
  WAVE_SPEED_MULT: 0.7,
  WAVE_AMPLITUDE: 30,
  WAVE_FREQUENCY: 3,
  PROJECTILE_MARGIN: 20,

  // Rifts
  RIFT_OPEN_DURATION: 0.3,
  RIFT_VISUAL_RADIUS: 20,

  // Particles
  MAX_PARTICLES: 200,
  DEATH_PARTICLE_COUNT: 50,
  HIT_PARTICLE_COUNT: 15,
  NEAR_MISS_PARTICLE_COUNT: 12,
  RIFT_PARTICLE_COUNT: 5,

  // Shake intensity
  SHAKE_HIT: 0.35,
  SHAKE_DEATH: 0.8,
  SHAKE_NEAR_MISS: 0.1,
  SHAKE_MILESTONE: 0.2,

  // Fog
  FOG_INITIAL_RADIUS: 300,
  FOG_SHRINK_RATE: 18,
  FOG_MIN_RADIUS: 80,

  // Colors
  BG_COLOR: '#060612',
  ACCENT: '#2fd299',
  ACCENT_DIM: 'rgba(47, 210, 153, 0.04)',
  PLAYER_COLOR: '#2fd299',
  ORB_COLOR: '#ff3366',
  BOLT_COLOR: '#ffaa00',
  WAVE_COLOR: '#6644ff',
  HUD_COLOR: '#2fd299',
  HUD_DIM: '#93aac9',
  RIFT_COLOR: '#2fd299',
  FOG_COLOR: 'rgba(6, 6, 18, 0.92)',
  HIT_FLASH_COLOR: '#ffffff',
  DEATH_COLOR: '#ff3366',

  // HUD
  HUD_FONT_LARGE: '600 24px monospace',
  HUD_FONT_MEDIUM: '600 18px monospace',
  HUD_FONT_SMALL: '500 14px monospace',
  HUD_FONT_TITLE: '700 36px monospace',
  HUD_FONT_COUNTDOWN: '700 72px monospace',

  // Grid
  GRID_SPACING: 40,
  GRID_DOT_RADIUS: 1,
} as const;
